### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by drewdeally** [kai-niemi/roach-bench-orders#1]
add to orders the ability to specify deliv_country_code

create-orders --num-threads 96 --country_code=

CREATE TABLE t_order (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  bill_address1 VARCHAR(255) NULL,
  bill_address2 VARCHAR(255) NULL,
  bill_city VARCHAR(255) NULL,
  bill_country_code VARCHAR(16) NULL,
  bill_country_name VARCHAR(16) NULL,
  bill_postcode VARCHAR(16) NULL,
  bill_to_first_name VARCHAR(255) NULL,
  bill_to_last_name VARCHAR(255) NULL,
  deliv_to_first_name VARCHAR(255) NULL,
  deliv_to_last_name VARCHAR(255) NULL,
  deliv_address1 VARCHAR(255) NULL,
  deliv_address2 VARCHAR(255) NULL,
  deliv_city VARCHAR(255) NULL,
  deliv_country_code VARCHAR(16) NULL,
  deliv_country_name VARCHAR(16) NULL,
  deliv_postcode VARCHAR(16) NULL,
  status VARCHAR(64) NULL,
  amount DECIMAL(19,2) NULL,
  currency VARCHAR(64) NULL,
  customer_id UUID NOT NULL,
  payment_method_id UUID NOT NULL,
  date_updated TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp():::TIMESTAMPTZ,
  date_placed TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp():::TIMESTAMPTZ,
  CONSTRAINT "primary" PRIMARY KEY (id ASC),
  FAMILY "primary" (id, bill_address1, bill_address2, bill_city, bill_country_code, bill_country_name, bill_postcode, bill_to_first_name, bill_to_last_name, deliv_to_first_name, deliv_to_last_name, deliv_address1, deliv_address2, deliv_city, deliv_country_code, deliv_country_name, deliv_postcode, status, amount, currency, customer_id, payment_method_id, date_updated, date_placed)
)

**Comment by kai-niemi** [comment]
Added parameter for country code. 
Merged alt-1 to main branch.
